name: "main"
permissions:
    contents: write

on:
    push:
        branches: [main]

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
    push-containers:
        strategy:
            matrix:
                include:
                    - arch: amd64
                      runner: blacksmith-2vcpu-ubuntu-2404
                      platform: linux/amd64
                    - arch: arm64
                      runner: blacksmith-2vcpu-ubuntu-2404-arm
                      platform: linux/arm64
        runs-on: ${{ matrix.runner }}
        permissions:
            contents: read
            packages: write
        env:
            TAG: ghcr.io/${{ github.repository_owner }}/basalt-web:main
        steps:
            - uses: actions/checkout@v5
            - name: Setup Docker Builder
              uses: useblacksmith/setup-docker-builder@v1
            - name: Log in to GHCR
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Docker image
              # Using Blacksmith to take advantage of persistence of Docker caching
              uses: useblacksmith/build-push-action@v2
              with:
                  context: .
                  file: ./Dockerfile
                  platforms: ${{ matrix.platform }}
                  push: true
                  tags: ${{ env.TAG }}-${{ matrix.arch }}

    manifest:
        needs: push-containers
        runs-on: ubuntu-24.04
        permissions:
            contents: read
            packages: write
        steps:
            - name: Log in to GHCR
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Create and push multi-arch manifest for main
              run: |
                  docker buildx imagetools create \
                      -t ghcr.io/${{ github.repository_owner }}/basalt-web:main \
                      ghcr.io/${{ github.repository_owner }}/basalt-web:main-amd64 \
                      ghcr.io/${{ github.repository_owner }}/basalt-web:main-arm64
