name: "main"
permissions:
    contents: write

on:
    push:
        branches: [main]

concurrency:
    group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
    cancel-in-progress: true

jobs:
    push-containers:
        runs-on: blacksmith-2vcpu-ubuntu-2404-arm
        permissions:
            contents: read
            packages: write
        env:
            DOCKERFILE: dockerfile
            TAG: ghcr.io/${{ github.repository_owner }}/basalt-web:main
        steps:
            - uses: actions/checkout@v4
            - name: Setup Docker Builder
              uses: useblacksmith/setup-docker-builder@v1
            - name: Log in to GHCR
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Build and push Docker image
              # Using Blacksmith to take advantage of persistence of Docker caching
              uses: useblacksmith/build-push-action@v2
              with:
                  context: .
                  file: ./containers/${{ env.DOCKERFILE }}
                  platforms: linux/amd64,linux/arm64
                  push: true
                  tags: ${{ env.TAG }}
