name: Cleanup PR Images

on:
    pull_request:
        types:
            - closed # runs on merge or close

jobs:
    cleanup:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - name: Log in to GHCR
              uses: docker/login-action@v3
              with:
                  registry: ghcr.io
                  username: ${{ github.actor }}
                  password: ${{ secrets.GITHUB_TOKEN }}

            - name: Delete PR image tag
              run: |
                  skopeo delete docker://ghcr.io/${{ github.repository }}:dev-pr-${{ github.event.number }}
